version: '3.8'

services:
  database:
    image: postgres:16.1-alpine3.18
    container_name: mikro-orm-database
    restart: always
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-deswal}
      - POSTGRES_DB=${DB_DATABASE:-mikro_orm_db}
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: mikro-orm-pgadmin
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - database
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  backend:
    container_name: mikro-orm-crud
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT:-8080}:8080"
    volumes:
      - .:/app
    restart: on-failure
    tty: true
    stdin_open: true
    depends_on:
      - database
    env_file:
      - .env

volumes:
  pg_data: {}
  pgadmin_data: {}
